name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Container image build
        run: echo "Container image build"
      - name: Container image push to registry
        run: echo "Container image push to registry"
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Cloud provider authentication
        run: echo "Cloud provider authentication"
      - name: KubeConfig setup
        run: echo "KubeConfig setup"
      - name: Deployment with kubectl
        run: echo "Deployment with kubectl"
