name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./kube-news/src
          file: ./kube-news/src/Dockerfile
          push: true
          tags: |
            lucasguima/kube-news:0.3.${{ github.run_number }}
            lucasguima/kube-news:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Cloud provider authentication
        run: echo "Cloud provider authentication"
      - name: KubeConfig setup
        run: echo "KubeConfig setup"
      - name: Deployment with kubectl
        run: echo "Deployment with kubectl"
